//
//  LoginModels.swift
//  CleanSwiftDemoWithCoreData
//
//  Created by Jorge Rebollo Jimenez on 21/05/18.
//  Copyright (c) 2018 personal. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
}
